### ISSUE TITLE
Lack of memory available in the subs for writing messages

### ISSUE THREAD

**Issue by x-tec2017** [Pinacolada64/ImageBBS#21]

**Comment by x-tec2017** [comment]
The amount of free memory available for writing messages in the subs is inversely proportional to the number of directory entries. This can limit the user to only a few lines for posting or replying to messages.

**Comment by x-tec2017** [comment]
Reduced the maximum number of directory entries to 30 in the subs by modifying +.MM.sb-post line 4084 and +/NM.netsub3 line 4058.  Changed >59 to >29 in both program modules.

**Comment by Pinacolada64** [comment]
While that works for now, I'd really lke to investigate loading the sub-board directories (SB, UD and UX) into structs. They're stored in a different area of memory (currently not sure where), unlike arrays which are stored in the limited amount of free RAM past the end of `im` and the top of BASIC.

If my hunch is correct, while using the subs, if something gets modified (file download count incremented, new post/response written), that particular directory entry could be written back to the respective `d.*` file at quit to maintain backwards compatability.

Maybe, _maybe_ this could be used to break the 60 entry limit - rather than load the entire directory into RAM, keep the `d.*` file open on disk and query it instead. This would be slower, but everything is a trade-off. Faster scans from RAM mean fewer entries, slower scans means holding the disk file open (perhaps only until a post got read; you have to juggle internal disk buffers on a 1541 at least, I *think* there's a limit of 2 REL files open at once? no clue about more modern drives like CMD/LTK. Will have to research.)

**Comment by x-tec2017** [comment]
The CMD could probably handle it but the Lt.K, not. The Lt.K can only open
one rel file at a time.

**Comment by Pinacolada64** [comment]
Good to know!

**Comment by jayctheriot** [comment]
As a "quick fix" I drop to local mode FG and get back to responding.  After garbage collection, 253 lines are available.

If there was a way to force garbage collection prior to opening the editor, it may provide a fix.

**Comment by x-tec2017** [comment]
Jay, you will only see 253 lines available if you are in local or
pseudo-local (zz) mode. You don't really have that many lines available but
the amount of memory available will be displayed in bytes in the editor. If
you're not in local or zz mode, the editor will display the actual number
of lines available.  Still, your method of doing a FG will provide more
lines usually.  There is a gosub in the im file that can be called prior to
loading the editor or simply insert &,40 into the basic file just prior to
entering the editor.
