### ISSUE TITLE
Cursor Menu - Dialogs skewed

### ISSUE THREAD

**Issue by ThaDoctor72** [Pinacolada64/ImageBBS#25]
In an area where dialog menus (yellow overlays) are prominent (i.e.: GF maint or options menus) the only option is to use the letter/number item to access the options.  The cursor appears at the bottom of the screen, and no marker seems to be present anywhere else on the screen.

**Comment by DarkstarII** [comment]
This must have been a work in progress todo item. I have also seen the number of entries are limited that are able to show up on the screen that you add, once the 5, 6 or 7 entries are there the cursor selection no longer grabs the correct entry after a certain number and gets thrown off by 1 line when selecting it or if you added to many items they just do not show up on the list.

**Comment by ThaDoctor72** [comment]
X-Tec mentioned in a different forum that this was due to the sysop screen being opened.  Pressing f1 to close it (or being a remote user) will have a corrected representation of the cursor menu

**Comment by DarkstarII** [comment]
I am able to reproduce the issue without using any mentioned changes and it works UNTIL. Maybe the problem description is mis-understood. I added 9 entries in my Movie Files directory from the main GF menu called Movie Files inside the directory I have a max limit of 9 movie files showing. If I cursor to the Maintenance option it grabs the Return to Main Menu code If I choose the Other Options it grabs the Maintenance Options code. This is caused by having 9 entries or more listed which is causing the entire menu to bump up lines ex if I had 15 movies listed the top menu would scroll off the screen and cause cursor locations for what it thinks it is on is way off. So the max entries is going to be 8 in order for it to work correctly and the 8th entry would need to be another directory link entry to show more movies. I do not have the BBS screen showing when this occurs and this makes it an issue for the SysOp unless they understand the reason of the limitation running from local logon mode.

**Comment by x-tec2017** [comment]
This issue can be closed.
