### ISSUE TITLE
+.access - Downloads per call only one digit

### ISSUE THREAD

**Issue by ThaDoctor72** [Pinacolada64/ImageBBS#26]
Is this by design that the data field only allows one character?  I can't think of a reason to give users less than 10 downloads per call.  If that's the case, I'll just give them unlimited downloads and modify the credit ratio to allow 20-30 for most generic access levels.
Subops and Maint users get unlimited anyway.  At least that's how I roll.
Otherwise, fix field 20 input to allow more than one character.

**Comment by x-tec2017** [comment]
Tested and duplicated issue. 
The downloads allowed per call is held in the da% variable. 
While Image 1.2 retrieved the da% variable from e.data as assigned to each access group, Image 2.0 gets the da% variable from the flag #20 in each users account in u.config. The user flags are set to a hard 20 position entry and is impractical to change the flag length. However, the fix is easy by giving the user 10 times the single digit number stored in position 20.

Change im at the end of line 1638 to da%=a*10
Change +.ED line 3294 by inserting *10 just prior to the last quotation mark.
Change +/IM.access line 4110 by inserting *10 just prior to the last quotation mark.

This will allow Downloads/Call to equal 0 to 90 in multiples of 10. (0 still equals unlimited)
Times 10 is just a suggestion. It could be any single digit number 0-9.
Asking for comments. If everyone agrees this is a good way to go, it will become standard.

**Comment by ThaDoctor72** [comment]
Neat workaround. It will do for now. Especially since speed is no longer an issue for non dialup boards.

**Comment by DarkstarII** [comment]
My Comment:
Great work around coding but is it really practical for ALL users or just 5 Sysops and Subops etc.
Back in the day the coding concept was written with the defined record formats and user access levels.
Time was the issue on how long before the BBS would let another user on during download/uploads and would have to logoff and back on giving another user a chance to get on the BBS, Unless I'm a special user. I"m a restricted user with 90 minutes or less and logoff/logon again or I have unlimited time. Nowadays people use the D64 D81 formats so if I"m access level 4 and can download 40 files a call how many D81 files can I download in 90 minutes. 40? a call before my time runs out and have to login again.
We are the 8 bit Masters!

**Comment by x-tec2017** [comment]
This issue can be closed
