### ISSUE TITLE
Message move utility gets "stuck"

### ISSUE THREAD

**Issue by Pinacolada64** [Pinacolada64/ImageBBS#7]
`+.MU` (the message move utility, pity it doesn't work on 1.x) will load the message base directory, let me "get" a message to move, but then I can't "drop" it in the second message base I defined.

**Comment by x-tec2017** [comment]
The +.MU message move utility works for me on both IMW and WN2. I moved a message from one sub and dropped it into another and then back again. Two things to consider: 1. Moving a message from a networked sub to a different sub, networked or not, will cause issues if the message is responded to on another BBS carrying that networked message board. The response when it comes back will be sent to the original sub and show up as a new post.   To avoid the confusion, the MU utility when used should not allow moving messages on a networked message board and it should display a message stating that.  2. The MU command can be used while in the subs which would be the most convenient place to use it if the sysop sees a message that should be in a different topic message board. The ecs command calls +.MU as a goto and +.MU exits to 1812 which make s the sysop go back into the subs with the SB command to see the results or just continue reading messages. It might be better to make MU a gosub command and exit +.MU with a RETURN instead of goto1812.

**Comment by Pinacolada64** [comment]
Ah, so user error on my part about moving messages.

Those enhancements would be good to do. I agree it should be a subop/sysop command while in the sub-boards.

**Comment by x-tec2017** [comment]
The +.MU program is fine as is. No changes necessary. It is ok to move a message in a networked sub to an overflow sub and could be necessary at times. Running as a gosub would rob needed memory from the utility. Leave as a goto.

**Comment by x-tec2017** [comment]
This issue can be closed.

**Comment by Pinacolada64** [comment]
Agreed.
